### ISSUE TITLE
webkitStorageInfo/webkitIndexedDB deprecation warning

### ISSUE THREAD

**Issue by rclai** [JackAdams/constellation#4]
```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead. - setup.js:108
'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead. - setup.js:108
```

Using Chrome.

**Comment by JackAdams** [comment]
Yeah, noticed that, but not sure what to do:

```
for (var member in window) {
  if (window[member] instanceof ReactiveDict) {
    dictionaries.push({
      name: member,
      dict: window[member]
    });
  }
}
```

`window[member] instanceof ReactiveDict` is the offending LOC

**Comment by JackAdams** [comment]
Fixed in 1.1.7.

**Comment by luisherranz** [comment]
I have installed latest version of babrahams:constellation (0.1.10) and using constellation:console 1.2.2 in the background but still having this issue. 

It looks like the line affected is this one:
https://github.com/JackAdams/constellation/blob/master/client/lib/setup.js#L119

I am also having another warning: `'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.` in the exact same line.

**Comment by JackAdams** [comment]
Well, that's disappointing.  Thought I'd fixed that.

I'm open to suggestions on how to fix this.  The error doesn't seem to match the code, but it's definitely that line that's causing the problem.

In the meantime, it's ugly but harmless.

**Comment by JackAdams** [comment]
All right. Got a fix for this. It's not pretty, but it works.
I'll release a new version soon.

**Comment by JackAdams** [comment]
1.2.3 fixes this.

**Comment by luisherranz** [comment]
Wow, that was quick :smile: 

Thanks Jack!

**Comment by luisherranz** [comment]
I updated and it's fine here as well now. Thanks!

**Comment by JackAdams** [comment]
Cool. Thanks for the independent verification that all is well again.
